from kbqa.const import SEQUENCE_LABEL


SIMPLE_QUESTIONS_CONFIG = {
    "MAX_TRIPLETS": 50,
}

SEQUENCE_LABELING_ID2LABEL = {
    0: SEQUENCE_LABEL.NON_ANSWER,
    1: SEQUENCE_LABEL.ANSWER,
}
SEQUENCE_LABELING_LABEL2ID = {
    SEQUENCE_LABEL.NON_ANSWER: 0,
    SEQUENCE_LABEL.ANSWER: 1,
}
